// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"database/sql"
	"time"
)

type Session struct {
	ID        int32     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UserName  string    `json:"user_name"`
	Value     string    `json:"value"`
}

type User struct {
	Name      string         `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
	Photo     sql.NullString `json:"photo"`
}
